import { createContext, useState, useEffect } from 'react';
import arduino from '../../assets/arduino.JPG';
import audifonosnoisecancelling from '../../assets/audifonosnoisecancelling.JPG';
import batablancotallam from '../../assets/batablancotallam.JPG';
import batalabazul from '../../assets/batalabazul.JPG';
import block_watercolor_fabiano from '../../assets/block-watercolor-fabiano.jpg';
import botasdeseguridad from '../../assets/botasdeseguridad.jpg';
import calchp12cplatinum from '../../assets/calchp12cplatinum.JPG';
import calculadoracasio from '../../assets/calculadoracasio.png';
import candadolocker from '../../assets/candadolocker.JPG';
import casaca_termica_negra from '../../assets/casaca-termica-negra.jpg';
import cascoblanco from '../../assets/cascoblanco.JPG';
import clabe_c_a_lightning from '../../assets/clabe-c-a-lightning.JPG';
import codigocivilperuano from '../../assets/codigocivilperuano.JPG';
import discoduro1tb from '../../assets/discoduro1tb.JPG';
import fisica_serway from '../../assets/fisica-serway.JPG';
import guantes_de_cuero from '../../assets/guantes-de-cuero.JPG';
import implementossetdiseccion from '../../assets/implementossetdiseccion.JPG';
import ipadair4applepencil from '../../assets/ipadair4applepencil.jpg';
import lentesprotlab from '../../assets/lentesprotlab.JPG';
import libroanatomia from '../../assets/libroanatomia.WEBP';
import librocalculostewart from '../../assets/librocalculostewart.JPG';
import libroeconomiamankiw from '../../assets/libroeconomiamankiw.JPG';
import librofisicafreedman from '../../assets/librofisicafreedman.WEBP';
import libroguiapmbok from '../../assets/libroguiapmbok.WEBP';
import maqueta_adn_3d from '../../assets/maqueta-adn-3d.JPG';
import monitor24_ from '../../assets/monitor24.avif';
import mouselogitech from '../../assets/mouselogitech.JPG';
import multimetro from '../../assets/multimetro.JPG';
import pelotamikasa from '../../assets/pelotamikasa.JPG';
import portalaptop from '../../assets/portalaptop.JPG';
import protoboard from '../../assets/protoboard.JPG';
import quimicachang from '../../assets/quimicachang.JPG';
import raquetateniswilson from '../../assets/raquetateniswilson.JPG';
import raspberrypi4 from '../../assets/raspberrypi4.JPG';
import reglast from '../../assets/reglast.JPG';
import ropa_equipo_futbol from '../../assets/ropa-equipo-futbol.jpg';
import setaquarelaspinceles from '../../assets/setaquarelaspinceles.JPG';
import tecladoraredragon from '../../assets/tecladoraredragon.jpg';
import termostanley1l from '../../assets/termostanley1l.JPG';

export const PostContext = createContext();

export const PostProvider = ({ children }) => {
  const [posts, setPosts] = useState(() => {
    localStorage.removeItem('campuslend_posts');

    const savedPosts = localStorage.getItem('campuslend_posts');
    if (savedPosts) {
      try {
        return JSON.parse(savedPosts);
      } catch (error) {
        console.error('Error al cargar posts', error);
      }
    }
    return [
    {
      id: 1,
      status: 'lending',
      category: 'Tecnología',
      title: 'Calculadora Científica Casio',
      description:
        'Calculadora en perfecto estado fx-991EX. Ideal para exámenes de cálculo y matrices.',
      imageUrl: calculadoracasio,
      views: 125,
      isFavorite: false,
      timeAgo: 'hace 2 horas',
      authorId: 101,
      authorName: 'Ana Ruiz',
      authorAvatar:
        'https://ui-avatars.com/api/?name=Ana+Ruiz&background=00543D&color=fff',
      rating: 4.9,
      completedLoans: 14,
      loanDuration: 'Durante el ciclo',
      pickupLocation: 'Pabellón de Ciencias',
     },
    {
      id: 2,
      status: 'requesting',
      category: 'Libros',
      title: 'Física Universitaria Vol. 2',
      description:
        'Necesito el libro de Sears Zemansky, 14va edición. Lo cuidaré muy bien.',
      imageUrl: librofisicafreedman,
      timeAgo: 'hace 3 horas',
      isFavorite: false,
      authorId: 102,
      authorName: 'Luis Torres',
      authorAvatar:
        'https://ui-avatars.com/api/?name=Luis+Torres&background=00543D&color=fff',
      rating: 4.5,
      completedLoans: 3,
      loanDuration: '2 semanas',
      pickupLocation: 'Biblioteca Central',
    },
    {
      id: 3,
      status: 'lent',
      category: 'Materiales',
      title: 'Juego de Escuadras y Regla T',
      description:
        'Materiales de dibujo técnico, prestados por el ciclo actual.',
      imageUrl: reglast,
      returnDays: 14,
      isFavorite: false,
      authorId: 103,
      authorName: 'Carlos Gómez',
      authorAvatar:
        'https://ui-avatars.com/api/?name=Carlos+Gomez&background=00543D&color=fff',
      rating: 5.0,
      completedLoans: 28,
      loanDuration: '1 semana',
      pickupLocation: 'Patio de Arquitectura',
    },
    {
      id: 4,
      status: 'lending',
      category: 'Ropa',
      title: 'Bata de Laboratorio Talla M',
      description:
        'Bata blanca 100% algodón, limpia y planchada. Solo para laboratorios de química.',
      imageUrl: batablancotallam,
      views: 42,
      isFavorite: false,
      timeAgo: 'hace 5 horas',
      authorId: 104,
      authorName: 'María Pérez',
      authorAvatar:
        'https://ui-avatars.com/api/?name=Maria+Perez&background=00543D&color=fff',
      rating: 4.7,
      completedLoans: 8,
      loanDuration: 'A coordinar',
      pickupLocation: 'Laboratorio de Química',
    },
    {
      id: 5,
      status: 'requesting',
      category: 'Tecnología',
      title: 'Cargador de Laptop HP',
      description:
        'Busco un cargador de punta azul para HP Pavillion, el mío se malogró hoy.',
      imageUrl: clabe_c_a_lightning,
      timeAgo: 'hace 1 día',
      isFavorite: false,
      authorId: 105,
      authorName: 'Diego López',
      authorAvatar:
        'https://ui-avatars.com/api/?name=Diego+Lopez&background=00543D&color=fff',
      rating: 4.2,
      completedLoans: 1,
      loanDuration: 'Urgente (hoy)',
      pickupLocation: 'Cafetería Central',
    },
    {
      id: 6,
      status: 'lending',
      category: 'Tecnología',
      title: 'Mouse Inalámbrico Logitech',
      description: 'Mouse en perfecto estado, incluye pila. Útil si olvidaste el tuyo.',
      imageUrl: mouselogitech,
      views: 89,
      isFavorite: false,
      timeAgo: 'hace 6 horas',
      authorId: 106,
      authorName: 'Sofia Castro',
      authorAvatar: 'https://ui-avatars.com/api/?name=Sofia+Castro&background=00543D&color=fff',
      rating: 4.8,
      completedLoans: 12,
      loanDuration: '3 días',
      pickupLocation: 'Pabellón A',
    },
    {
      id: 7,
      status: 'requesting',
      category: 'Libros',
      title: 'Cálculo de Stewart 8va Ed.',
      description: 'Necesito el libro urgente para prepararme para el parcial.',
      imageUrl: librocalculostewart,
      timeAgo: 'hace 1 hora',
      isFavorite: false,
      authorId: 107,
      authorName: 'Juan Pérez',
      authorAvatar: 'https://ui-avatars.com/api/?name=Juan+Perez&background=00543D&color=fff',
      rating: 4.0,
      completedLoans: 2,
      loanDuration: '1 mes',
      pickupLocation: 'Biblioteca Central',
    },
    {
      id: 8,
      status: 'lending',
      category: 'Materiales',
      title: 'Multímetro Digital',
      description: 'Multímetro Truper, incluye cables. Funciona al 100%.',
      imageUrl: multimetro,
      views: 34,
      isFavorite: false,
      timeAgo: 'hace 1 día',
      authorId: 108,
      authorName: 'Elena Rojas',
      authorAvatar: 'https://ui-avatars.com/api/?name=Elena+Rojas&background=00543D&color=fff',
      rating: 5.0,
      completedLoans: 21,
      loanDuration: '1 semana',
      pickupLocation: 'Laboratorio de Electrónica',
    },
    {
      id: 9,
      status: 'requesting',
      category: 'Ropa',
      title: 'Zapatos de Seguridad Talla 40',
      description: 'Busco botines con punta de acero para la visita técnica del viernes.',
      imageUrl: botasdeseguridad,
      timeAgo: 'hace 2 días',
      isFavorite: false,
      authorId: 109,
      authorName: 'Miguel Sánchez',
      authorAvatar: 'https://ui-avatars.com/api/?name=Miguel+Sanchez&background=00543D&color=fff',
      rating: 4.6,
      completedLoans: 5,
      loanDuration: '3 días',
      pickupLocation: 'Cafetería de Letras',
    },
    {
      id: 10,
      status: 'lent',
      category: 'Otros',
      title: 'Candado para Casillero',
      description: 'Candado mediano con llave extra.',
      imageUrl: candadolocker,
      returnDays: 2,
      isFavorite: false,
      authorId: 110,
      authorName: 'Lucía Vega',
      authorAvatar: 'https://ui-avatars.com/api/?name=Lucia+Vega&background=00543D&color=fff',
      rating: 4.9,
      completedLoans: 17,
      loanDuration: 'Todo el ciclo',
      pickupLocation: 'Pasillo Principal',
    },
    {
      id: 11,
      status: 'lending',
      category: 'Tecnología',
      title: 'iPad Air 4 + Apple Pencil',
      description: 'Presto mi iPad por un par de horas si necesitas tomar apuntes urgentes y te quedaste sin batería.',
      imageUrl: ipadair4applepencil,
      views: 204,
      isFavorite: true,
      timeAgo: 'hace 20 min',
      authorId: 111,
      authorName: 'Fernando Cruz',
      authorAvatar: 'https://ui-avatars.com/api/?name=Fernando+Cruz&background=00543D&color=fff',
      rating: 4.9,
      completedLoans: 35,
      loanDuration: 'Horas',
      pickupLocation: 'Biblioteca Central',
    },
    {
      id: 12,
      status: 'requesting',
      category: 'Libros',
      title: 'Macroeconomía - Mankiw',
      description: 'Alguien tiene la 10ma edición? La necesito para mi trabajo grupal.',
      imageUrl: libroeconomiamankiw,
      timeAgo: 'hace 4 horas',
      isFavorite: false,
      authorId: 112,
      authorName: 'Valeria Ríos',
      authorAvatar: 'https://ui-avatars.com/api/?name=Valeria+Rios&background=00543D&color=fff',
      rating: 4.3,
      completedLoans: 1,
      loanDuration: '1 semana',
      pickupLocation: 'Facultad de Economía',
    },
    {
      id: 13,
      status: 'lent',
      category: 'Materiales',
      title: 'Protoboard Grande de 4 buses',
      description: 'Ideal para proyectos de circuitos complejos.',
      imageUrl: protoboard,
      returnDays: 7,
      isFavorite: false,
      authorId: 108,
      authorName: 'Elena Rojas',
      authorAvatar: 'https://ui-avatars.com/api/?name=Elena+Rojas&background=00543D&color=fff',
      rating: 5.0,
      completedLoans: 21,
      loanDuration: '2 semanas',
      pickupLocation: 'Laboratorio de Electrónica',
    },
    {
      id: 14,
      status: 'lending',
      category: 'Ropa',
      title: 'Casco Blanco de Obra',
      description: 'Casco estándar certificado. Limpio y sin quiñes.',
      imageUrl: cascoblanco,
      views: 12,
      isFavorite: false,
      timeAgo: 'hace 2 días',
      authorId: 113,
      authorName: 'Andrés Mendoza',
      authorAvatar: 'https://ui-avatars.com/api/?name=Andres+Mendoza&background=00543D&color=fff',
      rating: 4.8,
      completedLoans: 11,
      loanDuration: '1 día',
      pickupLocation: 'Facultad de Ing. Civil',
    },
    {
      id: 15,
      status: 'requesting',
      category: 'Otros',
      title: 'Balón de Vóley Mikasa',
      description: 'Buscamos una pelota para jugar un partido en las canchas de la universidad esta tarde.',
      imageUrl: pelotamikasa,
      timeAgo: 'hace 10 min',
      isFavorite: false,
      authorId: 114,
      authorName: 'Carmen Silva',
      authorAvatar: 'https://ui-avatars.com/api/?name=Carmen+Silva&background=00543D&color=fff',
      rating: 4.1,
      completedLoans: 4,
      loanDuration: '1 tarde',
      pickupLocation: 'Canchas Deportivas',
    },
    {
      id: 16,
      status: 'lending',
      category: 'Tecnología',
      title: 'Teclado Mecánico Redragon',
      description: 'Switches azules. Muy cómodo si tienes que programar por varias horas en la biblio.',
      imageUrl: tecladoraredragon,
      views: 145,
      isFavorite: false,
      timeAgo: 'hace 1 semana',
      authorId: 115,
      authorName: 'Raúl Ortiz',
      authorAvatar: 'https://ui-avatars.com/api/?name=Raul+Ortiz&background=00543D&color=fff',
      rating: 4.7,
      completedLoans: 19,
      loanDuration: '3 días',
      pickupLocation: 'Centro de Cómputo',
    },
    {
      id: 17,
      status: 'lent',
      category: 'Libros',
      title: 'Atlas de Anatomía - Netter',
      description: 'La biblia de medicina. Cuidar mucho por favor.',
      imageUrl: libroanatomia,
      returnDays: 20,
      isFavorite: true,
      authorId: 116,
      authorName: 'Patricia Romero',
      authorAvatar: 'https://ui-avatars.com/api/?name=Patricia+Romero&background=00543D&color=fff',
      rating: 5.0,
      completedLoans: 42,
      loanDuration: '1 mes',
      pickupLocation: 'Facultad de Medicina',
    },
    {
      id: 18,
      status: 'requesting',
      category: 'Materiales',
      title: 'Arduino Uno R3 original',
      description: 'Mi placa se quemó ayer y tengo presentación de tesis mañana. Ayuda por favor!',
      imageUrl: arduino,
      timeAgo: 'hace 1 hora',
      isFavorite: false,
      authorId: 117,
      authorName: 'Héctor Vidal',
      authorAvatar: 'https://ui-avatars.com/api/?name=Hector+Vidal&background=00543D&color=fff',
      rating: 4.4,
      completedLoans: 6,
      loanDuration: '2 días',
      pickupLocation: 'Pabellón de Sistemas',
    },
    {
      id: 19,
      status: 'lending',
      category: 'Ropa',
      title: 'Lentes Protectores 3M',
      description: 'Lentes de policarbonato para laboratorios de química o mecánica. Sin rayones.',
      imageUrl: lentesprotlab,
      views: 22,
      isFavorite: false,
      timeAgo: 'hace 3 días',
      authorId: 104,
      authorName: 'María Pérez',
      authorAvatar: 'https://ui-avatars.com/api/?name=Maria+Perez&background=00543D&color=fff',
      rating: 4.7,
      completedLoans: 8,
      loanDuration: '1 semana',
      pickupLocation: 'Laboratorio de Química',
    },
    {
      id: 20,
      status: 'lent',
      category: 'Otros',
      title: 'Calculadora Financiera HP',
      description: 'HP 12c Platinum. Ideal para finanzas corporativas.',
      imageUrl: calchp12cplatinum,
      returnDays: 4,
      isFavorite: false,
      authorId: 112,
      authorName: 'Valeria Ríos',
      authorAvatar: 'https://ui-avatars.com/api/?name=Valeria+Rios&background=00543D&color=fff',
      rating: 4.3,
      completedLoans: 1,
      loanDuration: '1 semana',
      pickupLocation: 'Facultad de Economía',
    },
    {
      id: 21,
      status: 'requesting',
      category: 'Tecnología',
      title: 'Monitor Externo 24"',
      description: 'Busco un monitor para un evento en el patio central de la facultad.',
      imageUrl: monitor24_,
      timeAgo: 'hace 5 horas',
      isFavorite: false,
      authorId: 114,
      authorName: 'Carmen Silva',
      authorAvatar: 'https://ui-avatars.com/api/?name=Carmen+Silva&background=00543D&color=fff',
      rating: 4.1,
      completedLoans: 4,
      loanDuration: '1 día',
      pickupLocation: 'Patio Central',
    },
    {
      id: 22,
      status: 'lending',
      category: 'Libros',
      title: 'Guía PMBOK 6ta Edición',
      description: 'El libro está forrado y tiene algunos resaltados, pero todas las hojas están perfectas.',
      imageUrl: libroguiapmbok,
      views: 56,
      isFavorite: false,
      timeAgo: 'hace 2 semanas',
      authorId: 113,
      authorName: 'Andrés Mendoza',
      authorAvatar: 'https://ui-avatars.com/api/?name=Andres+Mendoza&background=00543D&color=fff',
      rating: 4.8,
      completedLoans: 11,
      loanDuration: 'Todo el ciclo',
      pickupLocation: 'Facultad de Ing. Industrial',
    },
    {
      id: 23,
      status: 'lent',
      category: 'Materiales',
      title: 'Kit de Disección Acero Inox',
      description: 'Kit completo de 12 piezas. Se entrega esterilizado.',
      imageUrl: implementossetdiseccion,
      returnDays: 1,
      isFavorite: false,
      authorId: 116,
      authorName: 'Patricia Romero',
      authorAvatar: 'https://ui-avatars.com/api/?name=Patricia+Romero&background=00543D&color=fff',
      rating: 5.0,
      completedLoans: 42,
      loanDuration: '2 días',
      pickupLocation: 'Facultad de Medicina',
    },
    {
      id: 24,
      status: 'requesting',
      category: 'Ropa',
      title: 'Bata Azul de Laboratorio Talla M',
      description: 'Necesito una bata azul urgente para el lab de biología. Pago el alquiler si es necesario.',
      imageUrl: batalabazul,
      timeAgo: 'hace 30 min',
      isFavorite: false,
      authorId: 117,
      authorName: 'Héctor Vidal',
      authorAvatar: 'https://ui-avatars.com/api/?name=Hector+Vidal&background=00543D&color=fff',
      rating: 4.4,
      completedLoans: 6,
      loanDuration: '1 tarde',
      pickupLocation: 'Laboratorio de Biología',
    },
    {
      id: 25,
      status: 'lending',
      category: 'Otros',
      title: 'Raqueta de Tenis Wilson',
      description: 'Presto mi raqueta los martes y jueves que no la uso.',
      imageUrl: raquetateniswilson,
      views: 78,
      isFavorite: false,
      timeAgo: 'hace 4 días',
      authorId: 110,
      authorName: 'Lucía Vega',
      authorAvatar: 'https://ui-avatars.com/api/?name=Lucia+Vega&background=00543D&color=fff',
      rating: 4.9,
      completedLoans: 17,
      loanDuration: 'Por horas',
      pickupLocation: 'Complejo Deportivo',
    },
    {
      id: 26,
      status: 'requesting',
      category: 'Tecnología',
      title: 'Raspberry Pi 4',
      description: 'Busco Raspberry Pi para probar un script de Python. Solo la necesito un fin de semana.',
      imageUrl: raspberrypi4,
      timeAgo: 'hace 1 día',
      isFavorite: true,
      authorId: 106,
      authorName: 'Sofia Castro',
      authorAvatar: 'https://ui-avatars.com/api/?name=Sofia+Castro&background=00543D&color=fff',
      rating: 4.8,
      completedLoans: 12,
      loanDuration: '3 días',
      pickupLocation: 'Pabellón A',
    },
    {
      id: 27,
      status: 'lending',
      category: 'Libros',
      title: 'Código Civil Peruano Comentado',
      description: 'Tomo I y II. Edición 2022. Muy pesados, mejor si nos vemos en la facultad.',
      imageUrl: codigocivilperuano,
      views: 11,
      isFavorite: false,
      timeAgo: 'hace 1 mes',
      authorId: 109,
      authorName: 'Miguel Sánchez',
      authorAvatar: 'https://ui-avatars.com/api/?name=Miguel+Sanchez&background=00543D&color=fff',
      rating: 4.6,
      completedLoans: 5,
      loanDuration: '2 semanas',
      pickupLocation: 'Facultad de Derecho',
    },
    {
      id: 28,
      status: 'lent',
      category: 'Materiales',
      title: 'Set de Pinceles y Acuarelas',
      description: 'Pinceles de detalle fino y acuarelas Winsor & Newton.',
      imageUrl: setaquarelaspinceles,
      returnDays: 3,
      isFavorite: false,
      authorId: 103,
      authorName: 'Carlos Gómez',
      authorAvatar: 'https://ui-avatars.com/api/?name=Carlos+Gomez&background=00543D&color=fff',
      rating: 5.0,
      completedLoans: 28,
      loanDuration: '1 semana',
      pickupLocation: 'Patio de Arquitectura',
    },
    {
      id: 29,
      status: 'requesting',
      category: 'Ropa',
      title: 'Uniforme de Fútbol Talla L',
      description: 'Alguien que me preste una camiseta deportiva? Olvidé la mía y tengo partido oficial.',
      imageUrl: ropa_equipo_futbol,
      timeAgo: 'hace 2 horas',
      isFavorite: false,
      authorId: 107,
      authorName: 'Juan Pérez',
      authorAvatar: 'https://ui-avatars.com/api/?name=Juan+Perez&background=00543D&color=fff',
      rating: 4.0,
      completedLoans: 2,
      loanDuration: '1 día',
      pickupLocation: 'Camarines',
    },
    {
      id: 30,
      status: 'lending',
      category: 'Otros',
      title: 'Termo Stanley 1L',
      description: 'Mantiene el café caliente todo el día. Ideal si te toca amanecida en la biblioteca.',
      imageUrl: termostanley1l,
      views: 93,
      isFavorite: false,
      timeAgo: 'hace 3 semanas',
      authorId: 115,
      authorName: 'Raúl Ortiz',
      authorAvatar: 'https://ui-avatars.com/api/?name=Raul+Ortiz&background=00543D&color=fff',
      rating: 4.7,
      completedLoans: 19,
      loanDuration: 'A coordinar',
      pickupLocation: 'Centro de Cómputo',
    },
    {
      id: 31,
      status: 'lent',
      category: 'Tecnología',
      title: 'Auriculares Sony c/ Cancelación',
      description: 'Presto audífonos WH-1000XM4. Solo para usarse dentro de la biblioteca.',
      imageUrl: audifonosnoisecancelling,
      returnDays: 1,
      isFavorite: true,
      authorId: 111,
      authorName: 'Fernando Cruz',
      authorAvatar: 'https://ui-avatars.com/api/?name=Fernando+Cruz&background=00543D&color=fff',
      rating: 4.9,
      completedLoans: 35,
      loanDuration: 'Horas',
      pickupLocation: 'Biblioteca Central',
    },
    {
      id: 32,
      status: 'requesting',
      category: 'Libros',
      title: 'Química - Raymond Chang',
      description: 'Alguien que ya haya pasado Química General 1 que me preste su libro?',
      imageUrl: quimicachang,
      timeAgo: 'hace 4 días',
      isFavorite: false,
      authorId: 102,
      authorName: 'Luis Torres',
      authorAvatar: 'https://ui-avatars.com/api/?name=Luis+Torres&background=00543D&color=fff',
      rating: 4.5,
      completedLoans: 3,
      loanDuration: 'Todo el ciclo',
      pickupLocation: 'Facultad de Ciencias',
    },
    {
      id: 33,
      status: 'lending',
      category: 'Materiales',
      title: 'Maqueta de ADN 3D',
      description: 'Maqueta desarmable en perfecto estado. Sirve para exposiciones.',
      imageUrl: maqueta_adn_3d,
      views: 31,
      isFavorite: false,
      timeAgo: 'hace 5 días',
      authorId: 116,
      authorName: 'Patricia Romero',
      authorAvatar: 'https://ui-avatars.com/api/?name=Patricia+Romero&background=00543D&color=fff',
      rating: 5.0,
      completedLoans: 42,
      loanDuration: '1 semana',
      pickupLocation: 'Facultad de Medicina',
    },
    {
      id: 34,
      status: 'lent',
      category: 'Ropa',
      title: 'Guantes de Cuero para Soldar',
      description: 'Guantes de caña larga gruesos de seguridad industrial.',
      imageUrl: guantes_de_cuero,
      returnDays: 1,
      isFavorite: false,
      authorId: 113,
      authorName: 'Andrés Mendoza',
      authorAvatar: 'https://ui-avatars.com/api/?name=Andres+Mendoza&background=00543D&color=fff',
      rating: 4.8,
      completedLoans: 11,
      loanDuration: '1 día',
      pickupLocation: 'Talleres Generales',
    },
    {
      id: 35,
      status: 'requesting',
      category: 'Otros',
      title: 'Mochila Porta Laptop',
      description: 'El cierre de mi mochila se rompió. Alguien que me preste una mochila temporal?',
      imageUrl: portalaptop,
      timeAgo: 'hace 6 horas',
      isFavorite: false,
      authorId: 105,
      authorName: 'Diego López',
      authorAvatar: 'https://ui-avatars.com/api/?name=Diego+Lopez&background=00543D&color=fff',
      rating: 4.2,
      completedLoans: 1,
      loanDuration: '2 días',
      pickupLocation: 'Cafetería Central',
    },
    {
      id: 36,
      status: 'lending',
      category: 'Tecnología',
      title: 'Cargador iPhone (Tipo C a Lightning)',
      description: 'Presto mi cargador original si estás en apuros dentro del campus.',
      imageUrl: clabe_c_a_lightning,
      views: 412,
      isFavorite: false,
      timeAgo: 'hace 1 mes',
      authorId: 110,
      authorName: 'Lucía Vega',
      authorAvatar: 'https://ui-avatars.com/api/?name=Lucia+Vega&background=00543D&color=fff',
      rating: 4.9,
      completedLoans: 17,
      loanDuration: 'Horas',
      pickupLocation: 'Pasillo Principal',
    },
    {
      id: 37,
      status: 'requesting',
      category: 'Libros',
      title: 'Física para Ciencias - Serway',
      description: 'Busco Volumen 1. Si está subrayado no hay problema.',
      imageUrl: fisica_serway,
      timeAgo: 'hace 1 semana',
      isFavorite: false,
      authorId: 107,
      authorName: 'Juan Pérez',
      authorAvatar: 'https://ui-avatars.com/api/?name=Juan+Perez&background=00543D&color=fff',
      rating: 4.0,
      completedLoans: 2,
      loanDuration: 'Todo el ciclo',
      pickupLocation: 'Pabellón C',
    },
    {
      id: 38,
      status: 'lending',
      category: 'Materiales',
      title: 'Block Papel Fabriano A3 (x10 hojas)',
      description: 'Me sobraron 10 hojas de mi curso de dibujo. Las regalo/presto a quien las necesite.',
      imageUrl: block_watercolor_fabiano,
      views: 67,
      isFavorite: false,
      timeAgo: 'hace 2 días',
      authorId: 103,
      authorName: 'Carlos Gómez',
      authorAvatar: 'https://ui-avatars.com/api/?name=Carlos+Gomez&background=00543D&color=fff',
      rating: 5.0,
      completedLoans: 28,
      loanDuration: 'Definitivo',
      pickupLocation: 'Patio de Arquitectura',
    },
    {
      id: 39,
      status: 'lent',
      category: 'Ropa',
      title: 'Chaqueta de Invierno Negra',
      description: 'Cortavientos muy abrigador. Ideal para los que se quedan estudiando de noche.',
      imageUrl: casaca_termica_negra,
      returnDays: 2,
      isFavorite: false,
      authorId: 115,
      authorName: 'Raúl Ortiz',
      authorAvatar: 'https://ui-avatars.com/api/?name=Raul+Ortiz&background=00543D&color=fff',
      rating: 4.7,
      completedLoans: 19,
      loanDuration: '1 noche',
      pickupLocation: 'Centro de Cómputo',
    },
    {
      id: 40,
      status: 'lending',
      category: 'Tecnología',
      title: 'Disco Duro Externo 1TB',
      description: 'Presto mi HDD si necesitas hacer un backup urgente de tu tesis.',
      imageUrl: discoduro1tb,
      views: 134,
      isFavorite: true,
      timeAgo: 'hace 3 semanas',
      authorId: 106,
      authorName: 'Sofia Castro',
      authorAvatar: 'https://ui-avatars.com/api/?name=Sofia+Castro&background=00543D&color=fff',
      rating: 4.8,
      completedLoans: 12,
      loanDuration: '1 día',
      pickupLocation: 'Pabellón A',
    },
    ];
  });

  useEffect(() => {
    localStorage.setItem('campuslend_posts', JSON.stringify(posts));
  }, [posts]);

  const handleAddPost = (newPost) => {
    setPosts([newPost, ...posts]);
  };

  const handleDeletePost = (id) => {
    setPosts(posts.filter((post) => post.id !== id));
  };

  const handleUpdatePost = (updatedPost) => {
    setPosts(
      posts.map((post) => (post.id === updatedPost.id ? updatedPost : post)),
    );
  };

  return (
    <PostContext.Provider
      value={{
        posts,
        setPosts,
        handleAddPost,
        handleDeletePost,
        handleUpdatePost,
      }}
    >
      {children}
    </PostContext.Provider>
  );
};